---
title: "Collect Results from Agamemnon"
output:
  pdf_document: default
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

## Setup

Clear workspace
On O2 cluster
```{r}
rm(list=ls())
```

```{r}
knitr::opts_chunk$set(eval = FALSE)
```

Load packages
```{r}
library(tidyverse)
```

Make repaired taxonomy
```{r}
setwd("~/Projects/tcga_micro")
# read in phylogenetic tree from agamemnon
taxonomy <- read_csv("data/tcga_proj_taxonomy.csv")
taxonomy

# make repars to missing data in taxonomy tree
# if "---" is present, replace with reasonable substitute with flag
# eg Anelloviridae_Family
taxonomy_nomissing <- taxonomy %>%
  # all missing superkingdom data are viruses (manual check)
  # viruses are not classified in the same system as cellular life
  # will use term 'virus' for all viruses at superkingdom level
  mutate(Superkingdom = ifelse(Superkingdom == "---", "Virus", Superkingdom)) %>%
  # if genus is missing, fill in with a higher level
  mutate(Genus = 
    ifelse((Genus == "---" & Family != "---"), paste0(Family, "_Family"),
      ifelse((Genus == "---" & Order != "---"), paste0(Order, "_Order"),
        ifelse((Genus == "---" & Class != "---"), paste0(Class, "_Class"),
          ifelse((Genus == "---" & Phylum != "---"), paste0(Phylum, "_Phylum"),
            ifelse((Genus == "---" & Superkingdom != "---"), paste0(Superkingdom, "_Superkingdom"),
            Genus)))))) %>%
  # if family is missing, fill in with a higher level
  mutate(Family = 
    ifelse((Family == "---" & Order != "---"), paste0(Order, "_Order"),
      ifelse((Family == "---" & Class != "---"), paste0(Class, "_Class"),
        ifelse((Family == "---" & Phylum != "---"), paste0(Phylum, "_Phylum"),
          ifelse((Family == "---" & Superkingdom != "---"), paste0(Superkingdom, "_Superkingdom"),
          Family))))) %>%
  # if order is missing, fill in with a higher level
  mutate(Order = 
      ifelse((Order == "---" & Class != "---"), paste0(Class, "_Class"),
        ifelse((Order == "---" & Phylum != "---"), paste0(Phylum, "_Phylum"),
          ifelse((Order == "---" & Superkingdom != "---"), paste0(Superkingdom, "_Superkingdom"),
          Order)))) %>%
  # if class is missing, fill in with a higher level
  mutate(Class = 
      ifelse((Class == "---" & Phylum != "---"), paste0(Phylum, "_Phylum"),
        ifelse((Class == "---" & Superkingdom != "---"), paste0(Superkingdom, "_Superkingdom"),
          Class))) %>%
  # if phylum is missing, fill in with a higher level
  mutate(Phylum = 
      ifelse((Phylum == "---" & Superkingdom != "---"), paste0(Superkingdom, "_Superkingdom"),
          Phylum)) 

# save copy
taxonomy_nomissing %>% saveRDS("data/tcga_proj_taxonomy_nomissing.rds")
taxonomy_nomissing %>% write_csv("data/tcga_proj_taxonomy_nomissing.csv")
# move taxonomy nomissing to HPC with filezilla
# location: ~/tcga_micro in my personal storage
```

Setup on O2 cluster
```{bash, eval=FALSE, include=TRUE}
srun --pty -p interactive --mem 64G -t 0-06:00 /bin/bash
module load gcc/6.2.0
module load R/4.0.1
cd /n/scratch3/users/m/mw292/AGAMEMNON/TCGA/Results2
R
```

## Define function
```{r}
# test variables
input_dir <- "/n/scratch3/users/m/mw292/AGAMEMNON/TCGA/Results2/TCGA_HNSC"
output_dir <- "/n/scratch3/users/m/mjl62/agamemnon_counts/mode2"
tcga_project <- "HNSC"
```

```{r}
gather_counts <- function(input_dir, tcga_project){
  #
  # function to gather all agamemnon output files
  # path to directories as a quoted string as dir arguments
  # ok if nested in subdirectories
  # 4-letter TCGA project as project argument
  # before starting, ensure no duplicate file_ids
  # output is three new CSVs:
  #   counts table
  #   clinical data
  #   taxonomy key
  #
  # load required packages
  library(tidyverse)
  library(GenomicDataCommons)
  library(Matrix.utils)
  #
  # set constants: 
  output_dir = "/n/scratch3/users/m/mjl62/agamemnon_counts/mode2"
  #
  # read in repaired taxonomy with no missing data
  #
  # print starting message
  print(paste0("starting analysis of TCGA project ", tcga_project))
  #
  # get dataframe of paths to results.tab files with file uuids
  paths_df <- dir(path = input_dir, 
           recursive = TRUE, 
           include.dirs = FALSE, 
           full.names = TRUE) %>%
    enframe() %>%
    dplyr::filter(grepl("results.tab", value)) %>%
    separate(value, into = c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "file_id"),
             sep = "/", remove = FALSE) %>%
    dplyr::select(pathto = value, file_id)
  # get clinical data from file uuids
  # requires GenomicDataCommons
  file_uuids_vector <- paths_df %>%
    pull(file_id)
  conversion_table <- files(legacy = FALSE) %>%
    GenomicDataCommons::filter( ~ file_id %in% file_uuids_vector) %>%
    GenomicDataCommons::select(c("cases.case_id","cases.samples.submitter_id")) %>%
    results_all() %>%
    as_tibble() %>%
    unnest(cases) %>%
    unnest(samples) %>%
    dplyr::select(submitter_id, file_id, case_id) %>%
    separate(submitter_id, into = c("x1", "x2", "x3", NA), sep = "-") %>%
    unite(tcga_barcode, "x1", "x2", "x3", sep = "-")
  clin_data <- conversion_table %>%
    pull(case_id) %>%
    gdc_clinical() %>%
    reduce(left_join, by = "case_id")
  # get sample type out of GDC
  sample_type <- files(legacy = FALSE) %>%
    GenomicDataCommons::filter( ~ file_id %in% file_uuids_vector) %>%
    GenomicDataCommons::select("cases.samples.sample_type") %>%
    results_all() %>%
    as_tibble() %>%
    unnest(cases) %>%
    unnest(samples)
  # get aliquot ID out of GDC
  aliquot_id <- files(legacy = FALSE) %>% 
    GenomicDataCommons::filter( ~ file_id %in% file_uuids_vector) %>% 
    GenomicDataCommons::select("cases.samples.portions.analytes.aliquots.submitter_id") %>%
    results_all() %>%
    as_tibble() %>%
    unnest(cases) %>%
    unnest(samples) %>%
    unnest(portions) %>%
    unnest(analytes) %>%
    unnest(aliquots) %>%
    dplyr::select(file_id, aliquot_submitter_id = submitter_id)
  clin_df <- list(conversion_table, clin_data) %>%
    reduce(left_join, by = "case_id") %>%
    left_join(sample_type, by = "file_id") %>%
    left_join(aliquot_id, by = "file_id") %>%
    dplyr::select(file_id, 
                  tcga_barcode,
                  tcga_full_barcode = aliquot_submitter_id,
                  case_id, 
                  sample_type, 
                  everything())
  # make lookup data for colnames
  barcode_lookuptable <- clin_df %>%
    dplyr::select(tcga_barcode, file_id, case_id)
  #
  # read tsvs to a list of tibbles
  paths_list <- paths_df %>%
    pull(pathto) %>%
    as.list()
  names(paths_list) <- paths_df$file_id
  tsv_list <- map(paths_list, read_tsv)
  # pull off taxonomy labels and set aside
  taxonomy <- tsv_list[[1]] %>%
    dplyr::select(Superkingdom, 
                  Phylum, 
                  Class, 
                  Order, 
                  Family, 
                  Genus, 
                  Species, 
                  Scientific_Name, 
                  TaxID) %>%
    mutate(TaxID = as.character(TaxID))
  # read in taxonomy
  taxonomy_nomissing <- read_csv("~/tcga_micro/tcga_proj_taxonomy_nomissing.csv") %>%
    # expects all variables to be characters for downstream merging
    mutate(TaxID = as.character(TaxID))
  # get matrix of counts with file_id as colnames
  tsv_mat <- tsv_list %>%
    map(function(df){df %>% pull(NumCounts)}) %>%
    bind_cols() %>%
    as.matrix()
  rownames(tsv_mat) <- taxonomy$TaxID
  #
  # aggregate by rownames using Matrix.utils
  # add column for TCGA barcodes
  # add column for sample_type
  taxid_counts_tbl <- aggregate.Matrix(tsv_mat, row.names(tsv_mat)) %>%
    as.matrix() %>%
    as.data.frame() %>%
    rownames_to_column(var = "TaxID") %>%
    as_tibble()
  # counts by species
  species_counts_intermed <- taxid_counts_tbl %>%
    left_join(taxonomy_nomissing, by = "TaxID") %>%
    dplyr::select(Species, everything()) %>%
    dplyr::select(-Superkingdom, 
                  -Phylum, 
                  -Class,
                  -Order, 
                  -Family,
                  -Genus,
                  -Scientific_Name,
                  -TaxID)
  species_counts_mat <- species_counts_intermed %>%
    dplyr::select(-Species) %>%
    as.matrix()
  rownames(species_counts_mat) <- species_counts_intermed %>%
    pull(Species)
  species_counts_tbl <- aggregate.Matrix(species_counts_mat, row.names(species_counts_mat)) %>%
    as.matrix() %>%
    as.data.frame() %>%
    rownames_to_column(var = "Species") %>%
    as_tibble()
  # aggregate by rownames using Matrix.utils
  # add column for TCGA barcodes
  # add column for sample_type
  # counts by genus
  genus_counts_intermed <- taxid_counts_tbl %>%
    # join taxonomy lookup table
    left_join(taxonomy_nomissing, by = "TaxID") %>%
    # remove undesired columns
    dplyr::select(-Superkingdom, 
                  -Phylum, 
                  -Class,
                  -Order, 
                  -Family,
                  -Species,
                  -Scientific_Name,
                  -TaxID)
  # make a matrix with count labels as rownames
  genus_counts_mat <- genus_counts_intermed %>%
    dplyr::select(-Genus) %>%
    as.matrix()
  rownames(genus_counts_mat) <- genus_counts_intermed %>%
    pull(Genus)
  # aggregate by summation for matching rownames
  genus_counts_tbl <- aggregate.Matrix(genus_counts_mat, row.names(genus_counts_mat)) %>%
    as.matrix() %>%
    # convert back to dataframe
    as.data.frame() %>%
    rownames_to_column(var = "Genus") %>%
    as_tibble()
  # counts by kingdom
  king_counts_intermed <- taxid_counts_tbl %>%
    left_join(taxonomy_nomissing, by = "TaxID") %>%
    dplyr::select(Species, everything()) %>%
    dplyr::select(-Phylum, 
                  -Class,
                  -Order, 
                  -Family,
                  -Genus,
                  -Species,
                  -Scientific_Name,
                  -TaxID)
  king_counts_mat <- king_counts_intermed %>%
    dplyr::select(-Superkingdom) %>%
    as.matrix()
  rownames(king_counts_mat) <- king_counts_intermed %>%
    pull(Superkingdom)
  king_counts_tbl <- aggregate.Matrix(king_counts_mat, row.names(king_counts_mat)) %>%
    as.matrix() %>%
    as.data.frame() %>%
    rownames_to_column(var = "Superkingdom") %>%
    as_tibble()
   # counts by phylum
  phylum_counts_intermed <- taxid_counts_tbl %>%
    left_join(taxonomy_nomissing, by = "TaxID") %>%
    dplyr::select(Species, everything()) %>%
    dplyr::select(-Superkingdom, 
                  -Class,
                  -Order, 
                  -Family,
                  -Genus,
                  -Species,
                  -Scientific_Name,
                  -TaxID)
  phylum_counts_mat <- phylum_counts_intermed %>%
    dplyr::select(-Phylum) %>%
    as.matrix()
  rownames(phylum_counts_mat) <- phylum_counts_intermed %>%
    pull(Phylum)
  phylum_counts_tbl <- aggregate.Matrix(phylum_counts_mat, row.names(phylum_counts_mat)) %>%
    as.matrix() %>%
    as.data.frame() %>%
    rownames_to_column(var = "Phylum") %>%
    as_tibble()
  # counts by taxid/scientific_name
  taxid_counts_intermed <- taxid_counts_tbl %>%
    left_join(taxonomy_nomissing, by = "TaxID") %>%
    dplyr::select(Scientific_Name, everything()) %>%
    dplyr::select(-Superkingdom, 
                  -Class,
                  -Order, 
                  -Family,
                  -Genus,
                  -Species,
                  -Phylum,
                  -TaxID)
  taxid_counts_mat <- taxid_counts_intermed %>%
    dplyr::select(-Scientific_Name) %>%
    as.matrix()
  rownames(taxid_counts_mat) <- taxid_counts_intermed %>%
    pull(Scientific_Name)
  taxid_counts_tbl <- aggregate.Matrix(taxid_counts_mat, row.names(taxid_counts_mat)) %>%
    as.matrix() %>%
    as.data.frame() %>%
    rownames_to_column(var = "Scientific Name") %>%
    as_tibble()
  #
  #
  # write taxID counts out as CSV
  write_csv(taxid_counts_tbl, 
            paste0(output_dir, 
                   "/", 
                   tcga_project, 
                   "_taxID_counts.csv"))
  # write Species counts out as CSV
  write_csv(species_counts_tbl, 
            paste0(output_dir, 
                   "/", 
                   tcga_project, 
                   "_species_counts.csv"))
  # write Genus counts out as CSV
  write_csv(genus_counts_tbl, 
            paste0(output_dir, 
                   "/", 
                   tcga_project, 
                   "_genus_counts.csv"))
  write_csv(king_counts_tbl,
            paste0(output_dir,
                   "/",
                   tcga_project,
                   "_kingdom_counts.csv"))
  write_csv(phylum_counts_tbl,
            paste0(output_dir,
                   "/",
                   tcga_project,
                   "_phylum_counts.csv"))
  # write clinical data out as CSV
  write_csv(clin_df,  
            paste0(output_dir, 
                   "/", 
                   tcga_project, 
                   "_clindata.csv"))
}
```

## Apply function

On O2 (interactive)
```{r, eval=FALSE, include=TRUE}
# navigate to target directory
setwd("/n/scratch3/users/m/mw292/AGAMEMNON/TCGA/Results2")

# make table of input variables
ftab_nostad <- list.files() %>%
  as_tibble() %>%
  dplyr::rename(directory = value) %>%
  dplyr::filter(grepl("TCGA_", directory)) %>%
  separate(directory, into = c(NA, "tcga_project", NA), remove = FALSE) %>%
  mutate(input_dir = paste0("/n/scratch3/users/m/mw292/AGAMEMNON/TCGA/Results2/", 
                            directory)) %>%
  dplyr::select(input_dir, tcga_project) %>%
  # remove projects with missing data
  dplyr::filter(tcga_project != "STAD") %>%
  dplyr::filter(tcga_project != "PRAD") %>%
  print() 

# add stad project labeled "mode2"
ftab_stad <- list.files() %>%
  as_tibble() %>%
  dplyr::rename(directory = value) %>%
  dplyr::filter(grepl("TCGA_", directory)) %>%
  separate(directory, into = c(NA, "tcga_project", NA), remove = FALSE) %>%
  mutate(input_dir = paste0("/n/scratch3/users/m/mw292/AGAMEMNON/TCGA/Results2/", 
                            directory)) %>%
  dplyr::select(input_dir, tcga_project) %>%
  # remove projects with missing data
  dplyr::filter(grepl("_mode2", input_dir)) %>%
  print() 

# combine tables 
ftab <- ftab_nostad %>%
  bind_rows(ftab_stad) %>%
  print()

# apply gather function to table
map2(ftab$input_dir, ftab$tcga_project, gather_counts)
```
